/** Stylesheet for the Skill Manager settings section (inlined once per mount). */

export const STYLE_TAG = 'skill-manager'
export const STYLE_CSS = [
  '.sm{display:flex;flex-direction:column;gap:14px;max-width:46rem;padding:2px 0 12px}',
  '.sm h3{margin:14px 0 4px;font-size:1rem}',
  '.sm p.sm-hint{margin:0;line-height:1.5;opacity:.75;font-size:.9em}',
  '.sm .sm-tabs{display:flex;gap:6px;flex-wrap:wrap;border-bottom:1px solid rgba(128,128,128,.25);padding-bottom:6px}',
  '.sm .sm-tab{font:inherit;padding:6px 12px;border-radius:8px;border:1px solid transparent;background:transparent;color:inherit;cursor:pointer;opacity:.7}',
  '.sm .sm-tab:hover{opacity:1;background:rgba(128,128,128,.08)}',
  '.sm .sm-tab[aria-selected="true"]{opacity:1;border-color:rgba(128,128,128,.4);background:rgba(128,128,128,.1)}',
  '.sm .sm-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}',
  '.sm .sm-toolbar .sm-grow{flex:1;min-width:180px}',
  '.sm .sm-input,.sm .sm-select,.sm .sm-textarea{font:inherit;padding:7px 10px;border-radius:7px;border:1px solid rgba(128,128,128,.35);background:transparent;color:inherit;max-width:100%}',
  '.sm .sm-textarea{resize:vertical;line-height:1.5;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.92em;width:100%;box-sizing:border-box}',
  '.sm .sm-field{display:flex;flex-direction:column;gap:5px;font-size:.92em}',
  '.sm .sm-check{display:flex;gap:8px;align-items:center;font-size:.92em;cursor:pointer}',
  '.sm .sm-row{display:flex;gap:10px;align-items:flex-start;padding:10px 12px;border:1px solid rgba(128,128,128,.22);border-radius:9px}',
  '.sm .sm-row + .sm-row{margin-top:6px}',
  '.sm .sm-row-body{flex:1;min-width:0;display:flex;flex-direction:column;gap:3px}',
  '.sm .sm-row-title{display:flex;gap:8px;align-items:center;flex-wrap:wrap;font-weight:600}',
  '.sm .sm-row-desc{margin:0;opacity:.75;line-height:1.45;font-size:.9em;overflow-wrap:anywhere}',
  '.sm .sm-row-sub{display:flex;gap:6px;align-items:center;flex-wrap:wrap;font-size:.82em;opacity:.85}',
  '.sm .sm-row-actions{display:flex;gap:6px;flex-shrink:0;flex-wrap:wrap}',
  '.sm .sm-badge{padding:1px 8px;border-radius:99px;font-size:.76em;border:1px solid rgba(128,128,128,.35);white-space:nowrap}',
  '.sm .sm-badge-ok{border-color:rgba(70,160,110,.6);color:#3f9d6b}',
  '.sm .sm-badge-warn{border-color:rgba(200,150,50,.6);color:#b8860b}',
  '.sm .sm-badge-bad{border-color:rgba(200,80,80,.6);color:#c2493f}',
  '.sm .sm-badge-mute{opacity:.65}',
  '.sm .sm-diagnostics{margin:4px 0 0;font-size:.84em;color:#c2493f;line-height:1.4}',
  '.sm .sm-button{font:inherit;padding:6px 12px;border-radius:8px;cursor:pointer;border:1px solid rgba(128,128,128,.4);background:rgba(128,128,128,.08);color:inherit}',
  '.sm .sm-button:hover:not(:disabled){background:rgba(128,128,128,.16)}',
  '.sm .sm-button:disabled{opacity:.5;cursor:not-allowed}',
  '.sm .sm-button-danger{border-color:rgba(200,80,80,.55);color:#c2493f}',
  '.sm .sm-button-primary{border-color:rgba(90,130,210,.6);background:rgba(90,130,210,.14)}',
  '.sm .sm-status{margin:2px 0 0;line-height:1.4;font-size:.88em}',
  '.sm .sm-status-ok{opacity:.8}',
  '.sm .sm-status-err{color:#c2493f}',
  '.sm .sm-empty{margin:8px 0;opacity:.6;font-size:.92em}',
  '.sm .sm-panel{border:1px solid rgba(128,128,128,.22);border-radius:10px;padding:12px;display:flex;flex-direction:column;gap:10px}',
  '.sm .sm-panel + .sm-panel{margin-top:12px}',
  '.sm .sm-grid2{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}',
  '.sm .sm-layer-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}',
  '.sm .sm-rule{margin:0;opacity:.75;font-size:.9em;line-height:1.5}',
  '.sm .sm-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap}',
  '.sm .sm-dialog-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:10px}',
  '.sm .sm-key{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.88em}',
  '.sm .sm-trash-actions{display:flex;gap:6px}',
].join('')
